### ISSUE TITLE
An authenticator that allows me to manually set the token

### ISSUE THREAD

**Issue by rzane** [webex/spark-android-sdk#11]
With the Javascript SDK, it's possible to initialize the spark client with an existing access token. That doesn't seem to be possible in this SDK.

Here's an example of how this might work:

```java
TokenAuthenticator authenticator = new TokenAuthenticator();
Spark spark = new Spark(activity.getApplication(), authenticator);
authenticator.setToken("eYJh...");
```

**Comment by kliu** [comment]
Hi @rzane 

You can easily make an Authenticator yourself for an existing access token.

For example, 

```java
public class TokenAuthenticator implements Authenticator {
	
	private String _token;
	
	public TokenAuthenticator(String token) {
		_token = token;
	}
	
	@Override
	public boolean isAuthorized() {
		return _token != null;
	}

	@Override
	public void deauthorize() {
		_token = null;
	}

	@Override
	public void getToken(CompletionHandler<String> handler) {
		handler.onComplete(new Result<String>() {
			@Override
			public boolean isSuccessful() {
				return true;
			}

			@Nullable
			@Override
			public SparkError getError() {
				return null;
			}

			@Nullable
			@Override
			public String getData() {
				return _token;
			}
		});
	}
}
```

**Comment by rzane** [comment]
Yeah I tried exactly this, but, that led to this error:

> No inject registered for members/com.myapp.TokenAuthenticator. You must explicitly add it to the injects option in one of your modules

It seems like the usable authenticators have to be defined [here](https://github.com/ciscospark/spark-android-sdk/blob/7ab21924744efa3aa9f1ef46d833df7d2a4bc861/sdk/src/main/java/com/ciscospark/androidsdk/internal/SparkModule.java#L132) when the SDK is compiled.

**Comment by rekhaagarwal** [comment]
Hey @kliu I am trying with the above mentioned method to set my spark instance with my token. But I am getting register timeout error while registering the device- spark.phone().register

Can you help me in this regard.

**Comment by kliu** [comment]
@rekhaagarwal Can you post the SDK logs for the issue.

**Comment by rekhaagarwal** [comment]
<img width="576" alt="spark" src="https://user-images.githubusercontent.com/21167009/37755483-a78391ba-2dcb-11e8-8acf-d182fda4a120.png">
[logs_spark.txt](https://github.com/ciscospark/spark-android-sdk/files/1836405/logs_spark.txt)
 hey @kliu attached the logcat logs and screenshot.

**Comment by DengQiming** [comment]
@rekhaagarwal I'll have a test on this issue, and I will let you know once there is any progress : )

**Comment by rekhaagarwal** [comment]
@DengQiming thanks a lot

**Comment by rekhaagarwal** [comment]
Hey @DengQiming Thanks for the analysis.  We get the access token by the below steps:
We enquire our own server about the spark account added to current user and if no spark account is present( not login) then our server gives the url: "https://staging.involvio.com/users/auth/cisco_spark?state=96612119ca58b378b31461e7f19a0bdf". 
When we hit the above user with our server token, our server will take us to similar to url:
**https://idbroker.webex.com/idb/saml2/jsp/doSSO.jsp?type=login&goto=https%3A%2F%2Fidbroker.webex.com%2Fidb%2Foauth2%2Fv1%2Fauthorize%3Fclient_id%3DC2bbafb5a9eae136c7288f0817faedab6ed15a15c4a36a1086a1dc64eb6842372%26redirect_uri%3Dhttps%253A%252F%252Fstaging.involvio.com%252Fcisco_spark_callback%26response_type%3Dcode%26state%3D96612119ca58b378b31461e7f19a0bdf%26scope%3Dspark%253Amessages_write%2520spark%253Arooms_read%2520spark%253Ateams_read%2520spark%253Amemberships_read%2520spark%253Amessages_read%2520spark%253Arooms_write%2520spark%253Apeople_read%2520spark%253Akms%2520spark%253Amemberships_write%2520spark%253Ateam_memberships_write**

and we do sign in with our cisco id and password and then get the access token after the sign in.

I am using the access token as below:

 TokenAuthenticator authenticator = new TokenAuthenticator("my_access_token");
            Spark spark = new Spark(InvolvioApplication.getInstance(), authenticator);


            spark.phone().register(new CompletionHandler<Void>() {
                @Override
                public void onComplete(Result<Void> result) {
                    if (result.isSuccessful()) {
                        // Device registered
                        Toast.makeText(ChatMessagesActivity.this, "success", Toast.LENGTH_SHORT).show();
                        //do something like call etc
                    }
                    else {
                        // Device not registered, and calls will not be sent or received
                        Toast.makeText(ChatMessagesActivity.this, "failure", Toast.LENGTH_SHORT).show();
                    }
                }
            });


        }

but in this getting above mentioned error- register time out and 
No inject registered for members/com.involvio.src.utils.TokenAuthenticator. You must explicitly add it to the 'injects' option in one of your modules.

**Comment by DengQiming** [comment]
Hi @rekhaagarwal The 'injects' related logs are just warning informations that we do not need to care about. From your provided log, I can find there is an error about 'REGISTER_DEVICE EXECUTING faulted', and I guess your account only has the scope with people & room functions, but without phone related functions, e.g. phone register & call. 
So, I suggest you have a test about searching people (spark.people().list()) or listing room (spark.room().list()) without calling   spark.phone().register() method. If it is successful, we can have a conclusion that the account scope is the problem.

**Comment by rekhaagarwal** [comment]
hey @DengQiming thanks for your help.

I checked with the spark.people().list()) , and its working fine for me. So it means its related to my spark account scope. 
I can see in the doc that using OAuth-based method, we send the scope parameter in authorization request but here I am using my access token which I got from my server so Is there any way to set the scopes from app?

**Comment by DengQiming** [comment]
@rekhaagarwal 
I think you can try to fill the query parameter of 'scope' as 'spark:all' in your register url (https://idbroker.webex.com/idb/saml2/jsp/doSSO.jsp?type=login&goto=https%3A%2F%2Fidbroker.webex.com%2Fidb%2Foauth2%2Fv1%2Fauthorize%3Fclient_id%3DC2bbafb5a9eae136c7288f0817faedab6ed15a15c4a36a1086a1dc64eb6842372%26redirect_uri%3Dhttps%253A%252F%252Fstaging.involvio.com%252Fcisco_spark_callback%26response_type%3Dcode%26state%3D96612119ca58b378b31461e7f19a0bdf%26**scope%3Dspark%253Amessages_write%2520spark%253Arooms_read%2520spark%253Ateams_read%2520spark%253Amemberships_read%2520spark%253Amessages_read%2520spark%253Arooms_write%2520spark%253Apeople_read%2520spark%253Akms%2520spark%253Amemberships_write%2520spark%253Ateam_memberships_write**), and it will work if your client_id matches with the scope applied for.

**Comment by rekhaagarwal** [comment]
@DengQiming thanks a lot! will try this.

**Comment by olivierproffit** [comment]
@rekhaagarwal is it solved, can we close this one ?

**Comment by olivierproffit** [comment]
@rekhaagarwal I think it's solved, so I am closing it but feel free to ping me over Webex Teams (oproffit@cisco.com) to further discuss if needed.
