### ISSUE TITLE
JWTAuthenticator getting 404

### ISSUE THREAD

**Issue by rzane** [webex/spark-android-sdk#12]
When the JWT authenticator sends a request to `/jwt/login`, it's getting back a 404. The `Authorization` header that is being sent along with the request is not the same the JWT that I'm passing to the `authorize()` method.

If I take the token that I passed to `authorize()`, and POST it verbatim to the `/jwt/login` endpoint, I am able to exchange it for an access token. So, whatever this library is doing to the JWT seems to be the culprit.

The JWT Authenticator was working just a few days ago, but something on the server appears to have changed.

**Comment by olivierproffit** [comment]
@rzane  I think it's solved, so I am closing it but feel free to ping me over Webex Teams (oproffit@cisco.com) to further discuss if needed.
