### ISSUE TITLE
Conflicts Dagger2: Program type already present: dagger.Module 

### ISSUE THREAD

**Issue by caka-ict** [webex/spark-android-sdk#29]
Hello,

Is there a way to fix the "Program type already present: dagger.Module" error when using Dagger2 in the Module app. It conflicts with Dagger 1 in your spark-android-sdk. Currently I'm using Android 3.1.3 and Gradle 4.4

Thank you!

**Comment by DengQiming** [comment]
@caka-ict We have noticed this issue, and already had a plan to update the Dagger version, but no detailed schedule right now.

**Comment by paintmonkey** [comment]
@caka-ict As a workaround you can try to shadow the dagger2 annotations as described here: https://fernandocejas.com/2016/08/03/android-dagger-1-and-2-living-together/ which worked for our project to let both libraries exists together.

**Comment by caka-ict** [comment]
Thanks for the feedback. I will wait for a version new to integrate this. I look forward to doing so soon.

**Comment by olivierproffit** [comment]
@caka-ict I am closing it this one since it's duplicate with this PR attached to the more recent Webex Android SDK https://github.com/webex/webex-android-sdk/pull/6 Feel free to comment it.
Also did the advice from @paintmonkey  worked for you @caka-ict
